# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
    branches:
      master:
        - step:
           script:
             - git remote add sync git@github.com:fjin/Exam4You.git
             - git checkout master
             - git pull    
             - git push sync dev
