name: Synch BitBucket via SSH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
#    branches: [ master ]
# uncomment to enable trigger only on push to specific branches e.g. master

# set the BB_REPO variable to the destination bitbucket workspace name
env:
  BB_ROOT: git@bitbucket.org:fanjin1/exam4you.git

jobs:
  syncbb:
    name: Synch from Github to Bitbucket using SSH
    runs-on: ubuntu-latest
    steps:
      - name: pull the github repo
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BITBUCKET_SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.BITBUCKET_KNOWN_HOSTS }}
          config: 
            Host bitbucket.org
              User git
              IdentityFile ~/.ssh/id_rsa
              IdentitiesOnly yes 

      - name: list all
        run: ls -al

      - uses: franzdiebold/github-env-vars-action@v1.0.0
      - name: sync with bitbucket
        run: |
          cd $GITHUB_WORKSPACE
          # update the whole repo including tags/branches but prune out deleted items
          echo synch with $BB_ROOT/$GITHUB_REPOSITORY_NAME
          git fetch --prune --unshallow 
          # make the bb repo a remote called sync
          git remote add sync $BB_ROOT/$GITHUB_REPOSITORY_NAME
          # force push the sync remote with all changes.
          git push --force --set-upstream -v --all sync
         
